name: Unity Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    tags: v*
    # branches: [ main ]
  pull_request:
    tags: v*
    # branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Unity - Build
        run: ./.scripts/build.bat
      
      - name: Create Archive
        run: Compress-Archive -Path ./build/* -DestinationPath ./game.zip

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.2
        with:
          name: Game
          path: ./game.zip
          retention-days: 9
         
  deploy:
    runs-on: self-hosted
    needs: [build]
    name: Deploy to itch.io
    env:
      BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
      itch_channel: <channel name> # e.g. jms777/gameName:web
      itch_url: <your game url> #e.g. https://jms777.itch.io/brackeys2021-1 
    steps:
      - name: Download Game Artifact
        uses: actions/download-artifact@v2.0.8
        with:
          name: Game
      - name: Configure Butler
        run: |
          Invoke-WebRequest -Uri https://broth.itch.ovh/butler/windows-amd64/LATEST/archive/default -OutFile butler.zip
          Expand-Archive -Path butler.zip -DestinationPath .
          ./butler.exe -V
          ./butler.exe login
      - name: Push to itch.io
        run: ./butler.exe push ./game.zip $env:itch_channel
      - name: Notify Discord
        if: success()
        run: Invoke-WebRequest -Method Post -Body @{content="New build deployed - $env:itch_url"} -Uri https://discord.com/api/webhooks/806215909349392416/50ZFHErCNojaeCcQ4x1U7RcwFYXoaPv5YG0uzeiioB7MNGQRGVYoqK_kZaUkocj3BMlK
